DEFAULT:
  # These formatting options will be used by default.
  options: "--style=otbs --attach-namespaces --attach-classes --indent=spaces=4 --convert-tabs --align-pointer=name --align-reference=name --keep-one-line-statements --pad-header --pad-oper"

proto-c:
  check: false
  include:
    - "/network_provisioning/proto-c/"

thirdparty:
  check: false
  include:
    - "/iqmath/"
    - "/qrcode/qrcodegen.*"
    - "/esp_jpeg/tjpgd/"
    - "/jsmn/include/jsmn.h"
