led_strip/examples/led_strip_rmt_ws2812:
  disable:
    - if: CONFIG_SOC_RMT_SUPPORTED != 1
      reason: Relevant only for RMT enabled targets

led_strip/examples/led_strip_spi_ws2812:
  enable:
    - if: (IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR >= 1) or (IDF_VERSION_MAJOR > 5)
      reason: Example uses some SPI driver features which was introduced in IDF v5.1
  disable:
    - if: CONFIG_SOC_GPSPI_SUPPORTED != 1
      reason: Relevant only for SPI enabled targets

esp_delta_ota:
  enable:
    - if: IDF_VERSION_MAJOR > 4
      reason: Example uses esp_app_format component which was introduced in IDF v5.0
  disable:
    - if: SOC_WIFI_SUPPORTED != 1
      reason: Relevant only for WiFi enabled targets

sh2lib/examples/http2_request:
  enable:
    - if: IDF_VERSION_MAJOR > 4 and INCLUDE_DEFAULT == 1
      reason: Example uses sh2lib component which was introduced in IDF v5.0

esp_jpeg/examples/get_started:
  enable:
    - if: IDF_VERSION_MAJOR > 4 and IDF_TARGET in ["esp32", "esp32s2", "esp32s3"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.0 and limited targets

catch2/examples/catch2-test:
  enable:
    - if: INCLUDE_DEFAULT == 1 or IDF_TARGET == "linux"
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Example relies on WHOLE_ARCHIVE component property which was introduced in IDF v5.0
    - if: IDF_VERSION_MAJOR == 5 and IDF_VERSION_MINOR < 1 and IDF_TARGET == "linux"
      reason: Docker container for release/v5.0 doesn't contain a C++ compiler

catch2/examples/catch2-console:
  disable:
    - if: IDF_VERSION_MAJOR < 5
      reason: Example relies on WHOLE_ARCHIVE component property which was introduced in IDF v5.0

l8w8jwt/examples/es256:
  enable:
    - if: IDF_VERSION_MAJOR > 4
      reason: Supported only on IDF versions with Mbed TLS v3.x
