esp_cli_commands/test_apps:
  enable:
    - if: IDF_TARGET in ["esp32", "linux"]

esp_cli_commands/examples/command_set:
  enable:
    - if: IDF_TARGET == "linux"

esp_cli_commands/examples/command_with_arg:
  enable:
    - if: IDF_TARGET == "linux"

esp_cli_commands/examples/dynamic_registration:
  enable:
    - if: IDF_TARGET == "linux"

esp_cli_commands/examples/integration_with_argtable:
  enable:
    - if: IDF_TARGET == "linux"

esp_cli_commands/examples/static_registration:
  enable:
    - if: IDF_TARGET == "linux"
