[book]
title = "X/YMODEM Documentation"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/espressif/idf-extra-components/tree/master/xymodem"
edit-url-template = "https://github.com/espressif/idf-extra-components/edit/master/xymodem/docs/{path}"
