/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

/*
 * Decode a progressive JPEG the way a slow link works: the file arrives in
 * CHUNK_SIZE pieces, and a complete (coarse, then sharper) picture is printed
 * after every scan.
 *
 * Two libjpeg features make that possible:
 *
 *   1. A data source that can suspend. fill_input_buffer() returns FALSE when
 *      no new bytes are in yet; libjpeg backs up to a safe restart point and
 *      returns to the caller. Repeating the same call after the next piece
 *      arrived continues where it stopped. That is the contract a socket or
 *      UART driver implements.
 *
 *   2. Buffered-image mode. A progressive file always needs a full-image
 *      coefficient buffer (~3 bytes/pixel for 4:2:0), whether or not this
 *      mode is on — jpeg_start_decompress() would otherwise swallow every
 *      scan and only then give you the final picture. buffered_image does
 *      not add a second framebuffer; it only lets jpeg_start_output() render
 *      after each scan. This example ships a 64x32 image so that buffer is
 *      about 6 KB.
 *
 * The main loop is the lockstep one from the "Buffered-image mode" chapter
 * of libjpeg.txt. Each pass prints the whole picture as ASCII plus a detail
 * score (mean neighbour difference) that climbs as the scans arrive.
 */

#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "jerror.h"
#include "jpeglib.h"

/*
 * Simulated packet size. Small on purpose so a scan boundary takes several
 * calls and the suspension path is really exercised. A real application
 * uses the size of its receive buffer.
 */
#define CHUNK_SIZE  64

/* Symbols generated by EMBED_FILES in main/CMakeLists.txt. */
extern const uint8_t image_prog_jpg_start[] asm("_binary_image_prog_jpg_start");
extern const uint8_t image_prog_jpg_end[] asm("_binary_image_prog_jpg_end");

/*
 * jpeg_source_mgr has to stay the first member: libjpeg only knows that
 * type, so a single cast recovers the whole struct from cinfo->src.
 */
typedef struct {
    struct jpeg_source_mgr pub;
    const uint8_t *data;
    size_t total;
    size_t released;    /* How much the application has handed over. */
    size_t offset;      /* How much the decoder has been offered. */
    size_t skipped;     /* Bytes skip_input_data() still has to drop. */
    bool eof;
    int suspends;
} chunk_source;

struct jpeg_error_mgr_ext {
    struct jpeg_error_mgr pub;
    jmp_buf setjmp_buffer;
};

static void jpeg_error_exit(j_common_ptr cinfo)
{
    struct jpeg_error_mgr_ext *err = (struct jpeg_error_mgr_ext *)cinfo->err;

    (*cinfo->err->output_message)(cinfo);
    longjmp(err->setjmp_buffer, 1);
}

/* ------------------------------------------------------------------------
 * The suspending data source
 * ------------------------------------------------------------------------ */

static boolean fill_input_chunk(j_decompress_ptr cinfo)
{
    chunk_source *src = (chunk_source *)cinfo->src;

    /* skip_input_data() cannot suspend, so leftover skip is applied here. */
    if (src->skipped > 0) {
        size_t skip = src->released - src->offset;

        if (skip > src->skipped) {
            skip = src->skipped;
        }
        src->offset += skip;
        src->skipped -= skip;
        if (src->skipped > 0) {
            src->suspends++;
            return FALSE;
        }
    }

    if (src->offset < src->released) {
        src->pub.next_input_byte = src->data + src->offset;
        src->pub.bytes_in_buffer = src->released - src->offset;
        src->offset = src->released;
        return TRUE;
    }

    if (src->eof) {
        /* Stream ended early: a synthetic EOI is the documented recovery. */
        static const JOCTET eoi[2] = { (JOCTET)0xFF, (JOCTET)JPEG_EOI };

        WARNMS(cinfo, JWRN_JPEG_EOF);
        src->pub.next_input_byte = eoi;
        src->pub.bytes_in_buffer = sizeof(eoi);
        return TRUE;
    }

    src->suspends++;
    return FALSE;
}

static void skip_input_chunk(j_decompress_ptr cinfo, long num_bytes)
{
    chunk_source *src = (chunk_source *)cinfo->src;

    if (num_bytes <= 0) {
        return;
    }

    if ((size_t)num_bytes <= src->pub.bytes_in_buffer) {
        src->pub.next_input_byte += num_bytes;
        src->pub.bytes_in_buffer -= (size_t)num_bytes;
        return;
    }

    src->skipped += (size_t)num_bytes - src->pub.bytes_in_buffer;
    src->pub.next_input_byte += src->pub.bytes_in_buffer;
    src->pub.bytes_in_buffer = 0;
}

static void chunk_init_source(j_decompress_ptr cinfo)
{
    (void)cinfo;
}

static void chunk_term_source(j_decompress_ptr cinfo)
{
    (void)cinfo;
}

static void jpeg_chunk_src(j_decompress_ptr cinfo, chunk_source *src,
                           const uint8_t *data, size_t len)
{
    memset(src, 0, sizeof(*src));
    src->data = data;
    src->total = len;

    src->pub.init_source = chunk_init_source;
    src->pub.fill_input_buffer = fill_input_chunk;
    src->pub.skip_input_data = skip_input_chunk;
    src->pub.resync_to_restart = jpeg_resync_to_restart;
    src->pub.term_source = chunk_term_source;
    src->pub.bytes_in_buffer = 0;
    src->pub.next_input_byte = NULL;

    cinfo->src = &src->pub;
}

/* Stands for "a packet arrived". Returns false once the whole file is in. */
static bool release_next_chunk(chunk_source *src)
{
    if (src->eof) {
        return false;
    }

    src->released += CHUNK_SIZE;
    if (src->released >= src->total) {
        src->released = src->total;
        src->eof = true;
    }
    return true;
}

/* ------------------------------------------------------------------------
 * Rendering
 * ------------------------------------------------------------------------ */

static int pixel_luma(JSAMPROW row, int x, int components)
{
    int sum = 0;

    for (int c = 0; c < components; c++) {
        sum += row[x * components + c];
    }
    return sum / components;
}

static char luma_to_ascii(int luma)
{
    static const char ramp[] = " .:-=+*#%@";

    return ramp[luma * (int)(sizeof(ramp) - 2) / 255];
}

/*
 * Print every output row of this pass as ASCII and accumulate a sharpness
 * score. cinfo->output_scanline is kept across a suspension, so repeating
 * this call continues where it stopped; rows already printed stay printed.
 */
static bool read_and_print_pass(j_decompress_ptr cinfo, JSAMPARRAY row,
                                unsigned int *diff_sum, unsigned int *diff_n)
{
    const int width = (int)cinfo->output_width;
    const int components = cinfo->output_components;

    while (cinfo->output_scanline < cinfo->output_height) {
        if (jpeg_read_scanlines(cinfo, row, 1) != 1) {
            return false;
        }

        int prev = -1;
        for (int x = 0; x < width; x++) {
            const int luma = pixel_luma(row[0], x, components);

            putchar(luma_to_ascii(luma));
            if (prev >= 0) {
                const int diff = luma - prev;

                *diff_sum += (unsigned int)(diff < 0 ? -diff : diff);
                (*diff_n)++;
            }
            prev = luma;
        }
        putchar('\n');
    }

    return true;
}

/* ------------------------------------------------------------------------
 * The example itself
 * ------------------------------------------------------------------------ */

static void decode_progressively(const uint8_t *data, size_t len)
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;
    chunk_source src;
    /* volatile: modified between setjmp and a possible longjmp. */
    volatile int passes = 0;

    memset(&cinfo, 0, sizeof(cinfo));
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buffer)) {
        printf("JPEG decode failed\n");
        jpeg_destroy_decompress(&cinfo);
        return;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_chunk_src(&cinfo, &src, data, len);

    while (jpeg_read_header(&cinfo, TRUE) == JPEG_SUSPENDED) {
        if (!release_next_chunk(&src)) {
            printf("JPEG header is incomplete\n");
            jpeg_destroy_decompress(&cinfo);
            return;
        }
    }

    printf("\n%s image, %ux%u, %d components, %u bytes\n",
           cinfo.progressive_mode ? "Progressive" : "Baseline",
           cinfo.image_width, cinfo.image_height, cinfo.num_components,
           (unsigned int)len);
    printf("releasing %u bytes at a time\n\n", (unsigned int)CHUNK_SIZE);

    if (!cinfo.progressive_mode) {
        printf("not a progressive JPEG; buffered-image mode is not needed\n");
        jpeg_destroy_decompress(&cinfo);
        return;
    }

    /* After the header: the library now knows the file has several scans. */
    cinfo.buffered_image = TRUE;
    jpeg_start_decompress(&cinfo);   /* reads no input in this mode */

    const JDIMENSION row_stride = cinfo.output_width * (JDIMENSION)cinfo.output_components;
    JSAMPARRAY row = (*cinfo.mem->alloc_sarray)((j_common_ptr)&cinfo, JPOOL_IMAGE,
                                                row_stride, 1);

    for (;;) {
        passes++;
        printf("\npass %d, %u of %u bytes received\n", passes,
               (unsigned int)src.released, (unsigned int)len);

        while (!jpeg_start_output(&cinfo, cinfo.input_scan_number)) {
            if (!release_next_chunk(&src)) {
                printf("input ended before the scan was complete\n");
                jpeg_destroy_decompress(&cinfo);
                return;
            }
        }

        unsigned int diff_sum = 0;
        unsigned int diff_n = 0;

        while (!read_and_print_pass(&cinfo, row, &diff_sum, &diff_n)) {
            if (!release_next_chunk(&src)) {
                printf("input ended before the image was complete\n");
                jpeg_destroy_decompress(&cinfo);
                return;
            }
        }

        while (!jpeg_finish_output(&cinfo)) {
            if (!release_next_chunk(&src)) {
                printf("input ended before the file was complete\n");
                jpeg_destroy_decompress(&cinfo);
                return;
            }
        }

        const int detail = (diff_n > 0) ? (int)(diff_sum / diff_n) : 0;

        printf("^ scan %d of %d, detail %d\n", cinfo.output_scan_number,
               cinfo.input_scan_number, detail);

        if (jpeg_input_complete(&cinfo) &&
                cinfo.input_scan_number == cinfo.output_scan_number) {
            break;
        }
    }

    printf("\ndecoded %d scans from %u bytes, %d suspensions\n",
           cinfo.input_scan_number, (unsigned int)src.released, src.suspends);

    while (!jpeg_finish_decompress(&cinfo)) {
        if (!release_next_chunk(&src)) {
            break;
        }
    }
    jpeg_destroy_decompress(&cinfo);
}

void app_main(void)
{
    printf("Progressive JPEG decoding, one chunk at a time\n");

    decode_progressively(image_prog_jpg_start,
                         (size_t)(image_prog_jpg_end - image_prog_jpg_start));

    printf("\ndone\n");
}
