/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

/*
 * Progressive JPEG decoding on ESP-IDF
 * ====================================
 *
 * A progressive JPEG is stored as a series of scans. The first scans carry
 * only the lowest-frequency coefficients, so after reading a few hundred
 * bytes of a 16 KB file the decoder can already render a complete, coarse
 * image; each following scan adds detail. That is what makes "show a preview
 * while the download is still running" possible on a slow link.
 *
 * This example shows the two libjpeg API pieces an application needs for
 * that, and nothing else: no display, no LCD, no extra component. Each
 * intermediate image is printed on the console as ASCII art.
 *
 *   1. A data source that can suspend. The embedded JPEG is cut into
 *      CHUNK_SIZE pieces. When the decoder asks for data and no piece has
 *      arrived yet, fill_input_buffer() returns FALSE; libjpeg then backs up
 *      to a safe restart point and returns to the application instead of
 *      failing. Repeating the very same call after the next piece arrived
 *      continues where it stopped, with no state lost. That is the contract
 *      a socket, a UART or a camera driver implements.
 *
 *   2. Buffered-image mode (cinfo.buffered_image = TRUE). The decoder keeps
 *      every coefficient it has seen, so each scan refines the buffered
 *      image and jpeg_start_output() can render it as many times as wanted.
 *
 * The main loop is the one from the "Buffered-image mode" chapter of
 * libjpeg.txt: every pass renders the scan that has just been received, so
 * the output stays in lockstep with the arriving data.
 *
 * For every scan the console shows how many bytes had been received, the
 * picture as it looked at that moment, and its "detail" figure: the average
 * difference between neighbouring pixels. Low and flat at first, growing
 * with every scan, which is progressive refinement made into a number.
 */

#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "jerror.h"
#include "jpeglib.h"

/*
 * The top-left corner of the image, printed at one character per pixel.
 *
 * Printing it 1:1 instead of scaled down keeps every detail the scans bring:
 * after the first scan each 8x8 block is one flat character, and later scans
 * gradually resolve the edges inside them.
 */
#define CROP_COLS  72
#define CROP_ROWS  26

/*
 * How many bytes the application releases to the decoder at a time. Small on
 * purpose, so that a scan boundary takes several calls and the suspension
 * path is really exercised. A real application would use the size of its
 * receive buffer here and hand over whatever a packet brings.
 */
#define CHUNK_SIZE  64

/* Symbols generated by EMBED_FILES in main/CMakeLists.txt. */
extern const uint8_t image_prog_jpg_start[] asm("_binary_image_prog_jpg_start");
extern const uint8_t image_prog_jpg_end[] asm("_binary_image_prog_jpg_end");

/*
 * The state of the chunked source.
 *
 * jpeg_source_mgr has to stay the first member: libjpeg only knows that
 * type, so a single cast recovers the whole struct from cinfo->src.
 */
typedef struct {
    struct jpeg_source_mgr pub;
    const uint8_t *data;   /* The whole JPEG, here in flash. */
    size_t total;          /* Size of the whole JPEG. */
    size_t released;       /* How much of it the application has released. */
    size_t offset;         /* How much of it the decoder has been offered. */
    size_t skipped;        /* Bytes to drop before the next piece is given. */
    bool eof;              /* Whole file released, only a fake EOI is left. */
} chunk_source;

static chunk_source s_src;      /* The one source this example decodes from. */
static int s_suspends;          /* How often the source said "not yet". */

/* Extended error manager: libjpeg requires error_exit() not to return. */
struct jpeg_error_mgr_ext {
    struct jpeg_error_mgr pub;
    jmp_buf setjmp_buffer;
};

static void jpeg_error_exit(j_common_ptr cinfo)
{
    struct jpeg_error_mgr_ext *err = (struct jpeg_error_mgr_ext *)cinfo->err;

    (*cinfo->err->output_message)(cinfo);
    longjmp(err->setjmp_buffer, 1);
}

/* ------------------------------------------------------------------------
 * The suspending data source
 * ------------------------------------------------------------------------ */

/*
 * Hand the decoder everything that has been released but not offered yet.
 *
 * Returning FALSE is not an error: it means "no data right now, ask me again
 * later". libjpeg then backs up to a safe restart point and returns to the
 * application, which repeats the very same call once the next piece arrived.
 */
static boolean fill_input_chunk(j_decompress_ptr cinfo)
{
    chunk_source *src = (chunk_source *)cinfo->src;

    /*
     * Bytes the decoder asked to skip but that were not buffered yet are
     * dropped here: this is the only place that sees new data.
     */
    if (src->skipped > 0) {
        size_t skip = src->released - src->offset;

        if (skip > src->skipped) {
            skip = src->skipped;
        }
        src->offset += skip;
        src->skipped -= skip;
        if (src->skipped > 0) {
            /* Not enough new data yet to skip over; wait for more. */
            s_suspends++;
            return FALSE;
        }
    }

    if (src->offset < src->released) {
        src->pub.next_input_byte = src->data + src->offset;
        src->pub.bytes_in_buffer = src->released - src->offset;
        src->offset = src->released;
        return TRUE;
    }

    if (src->eof) {
        /*
         * Everything has been released and the decoder still wants more,
         * which means the stream ended early. A synthetic EOI marker is the
         * documented way out: the decoder emits a truncation warning and
         * outputs whatever it has.
         */
        static const JOCTET eoi[2] = { (JOCTET)0xFF, (JOCTET)JPEG_EOI };

        WARNMS(cinfo, JWRN_JPEG_EOF);
        src->pub.next_input_byte = eoi;
        src->pub.bytes_in_buffer = sizeof(eoi);
        return TRUE;
    }

    /* Everything released has been consumed: suspend until more arrives. */
    s_suspends++;
    return FALSE;
}

/*
 * Skip over bytes the decoder is not interested in, such as an APPn marker.
 *
 * skip_input_data() is not allowed to suspend, so it can only give up what
 * is buffered; the rest is remembered in ->skipped and dropped by the next
 * fill_input_chunk().
 */
static void skip_input_chunk(j_decompress_ptr cinfo, long num_bytes)
{
    chunk_source *src = (chunk_source *)cinfo->src;

    if (num_bytes <= 0) {
        return;
    }

    if ((size_t)num_bytes <= src->pub.bytes_in_buffer) {
        src->pub.next_input_byte += num_bytes;
        src->pub.bytes_in_buffer -= (size_t)num_bytes;
        return;
    }

    src->skipped += (size_t)num_bytes - src->pub.bytes_in_buffer;
    src->pub.next_input_byte += src->pub.bytes_in_buffer;
    src->pub.bytes_in_buffer = 0;
}

static void chunk_init_source(j_decompress_ptr cinfo)
{
    /* jpeg_chunk_src() has already installed the state, nothing to do. */
}

static void chunk_term_source(j_decompress_ptr cinfo)
{
    /* The buffer belongs to the caller, nothing to free. */
}

/*
 * Install the chunked source. Nothing is released yet: the application
 * decides when the first piece arrives.
 */
static void jpeg_chunk_src(j_decompress_ptr cinfo, chunk_source *src,
                           const uint8_t *data, size_t len)
{
    memset(src, 0, sizeof(*src));
    src->data = data;
    src->total = len;

    src->pub.init_source = chunk_init_source;
    src->pub.fill_input_buffer = fill_input_chunk;
    src->pub.skip_input_data = skip_input_chunk;
    src->pub.resync_to_restart = jpeg_resync_to_restart;
    src->pub.term_source = chunk_term_source;
    src->pub.bytes_in_buffer = 0;
    src->pub.next_input_byte = NULL;

    cinfo->src = &src->pub;
    s_suspends = 0;
}

/*
 * Release the next piece of the file to the decoder.
 *
 * This stands for "a packet arrived" in a real application. Returns false
 * once the whole file has been released, which lets the caller bail out
 * instead of waiting for data that cannot come.
 */
static bool release_next_chunk(chunk_source *src)
{
    if (src->eof) {
        return false;
    }

    src->released += CHUNK_SIZE;
    if (src->released >= src->total) {
        src->released = src->total;
        src->eof = true;
    }
    return true;
}

/* ------------------------------------------------------------------------
 * Rendering
 * ------------------------------------------------------------------------ */

/* Average the channels of one pixel into a single brightness value. */
static int pixel_luma(JSAMPROW row, int x, int components)
{
    int sum = 0;

    for (int c = 0; c < components; c++) {
        sum += row[x * components + c];
    }
    return sum / components;
}

/* Dark to bright, so the crop reads like a picture on the console. */
static char luma_to_ascii(int luma)
{
    static const char ramp[] = " .:-=+*#%@";

    return ramp[luma * (int)(sizeof(ramp) - 2) / 256];
}

/*
 * The pixels of the current pass, one brightness value per pixel.
 *
 * File scope, so that they outlive the suspension points below: a pass can be
 * interrupted as often as the source runs dry and still yield one picture.
 */
static int s_gray[CROP_ROWS][CROP_COLS];
static int s_rows_read;                    /* Rows of this pass seen so far. */

/*
 * Read the output rows of the current pass and keep the ones in the crop.
 *
 * Everything needed comes from cinfo->output_scanline, which libjpeg keeps
 * across a suspension, so repeating this call simply continues where it
 * stopped. Rows outside the crop still have to be read: libjpeg hands them
 * out in order and never skips ahead.
 */
static bool read_pass_into_crop(j_decompress_ptr cinfo, JSAMPARRAY row)
{
    const int width = (int)cinfo->output_width;
    const int components = cinfo->output_components;

    while (cinfo->output_scanline < cinfo->output_height) {
        const int y = (int)cinfo->output_scanline;   /* Row about to be read. */

        if (jpeg_read_scanlines(cinfo, row, 1) != 1) {
            return false;       /* Suspended: repeat this call with more data. */
        }

        if (y < CROP_ROWS) {
            for (int x = 0; x < CROP_COLS && x < width; x++) {
                s_gray[y][x] = pixel_luma(row[0], x, components);
            }
            s_rows_read = y + 1;
        }
    }

    return true;
}

/*
 * Print the crop and return how sharp it is: the average difference between
 * neighbouring pixels. Low after the first scan, growing with every one
 * after it, which is progressive refinement made into a number.
 */
static int print_crop(void)
{
    unsigned int diff_sum = 0;

    for (int y = 0; y < s_rows_read; y++) {
        for (int x = 0; x < CROP_COLS; x++) {
            putchar(luma_to_ascii(s_gray[y][x]));
        }
        putchar('\n');
    }

    for (int y = 0; y < s_rows_read; y++) {
        for (int x = 1; x < CROP_COLS; x++) {
            const int diff = s_gray[y][x] - s_gray[y][x - 1];

            diff_sum += (unsigned int)(diff < 0 ? -diff : diff);
        }
    }

    return (int)(diff_sum / (unsigned int)(s_rows_read * (CROP_COLS - 1)));
}

/* ------------------------------------------------------------------------
 * The example itself
 * ------------------------------------------------------------------------ */

/*
 * Decode a progressive JPEG that arrives one chunk at a time, rendering the
 * buffered image after every scan.
 *
 * Every libjpeg call that consumes input can suspend, so each of them is
 * repeated until it reports success. That is exactly what an application
 * does when its data comes from a socket instead of from flash.
 */
static void decode_progressively(const uint8_t *data, size_t len)
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;
    volatile int passes = 0;
    int detail = 0;

    memset(&cinfo, 0, sizeof(cinfo));
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buffer)) {
        printf("JPEG decode failed\n");
        jpeg_destroy_decompress(&cinfo);
        return;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_chunk_src(&cinfo, &s_src, data, len);

    /* The frame header sits at the beginning; read it a chunk at a time. */
    while (jpeg_read_header(&cinfo, TRUE) == JPEG_SUSPENDED) {
        if (!release_next_chunk(&s_src)) {
            printf("JPEG header is incomplete\n");
            jpeg_destroy_decompress(&cinfo);
            return;
        }
    }

    /*
     * Buffered-image mode: the decoder keeps every coefficient it has seen,
     * so each scan refines the image and jpeg_start_output() can render it
     * as many times as wanted. It has to be selected after the header, which
     * is what tells the library that the file has several scans.
     */
    cinfo.buffered_image = TRUE;

    printf("\n%s image, %ux%u, %d components, %u bytes\n",
           cinfo.progressive_mode ? "Progressive" : "Baseline",
           cinfo.image_width, cinfo.image_height, cinfo.num_components,
           (unsigned int)len);
    printf("releasing %u bytes at a time\n\n", (unsigned int)CHUNK_SIZE);

    /* Buffered-image mode: jpeg_start_decompress() reads no input at all. */
    jpeg_start_decompress(&cinfo);

    for (;;) {
        passes++;
        printf("\npass %d, %u of %u bytes received\n", passes,
               (unsigned int)s_src.released, (unsigned int)len);

        /* Render the scan that has just been received. */
        while (!jpeg_start_output(&cinfo, cinfo.input_scan_number)) {
            if (!release_next_chunk(&s_src)) {
                printf("input ended before the scan was complete\n");
                goto cleanup;
            }
        }

        /*
         * One output row buffer, from the pool that lives for this output
         * pass. libjpeg hands out the rows in order, so whichever way they
         * are consumed, the whole pass has to be read to advance.
         */
        const JDIMENSION row_stride = cinfo.output_width * (JDIMENSION)cinfo.output_components;
        JSAMPARRAY row = (*cinfo.mem->alloc_sarray)((j_common_ptr)&cinfo, JPOOL_IMAGE,
                                                    row_stride, 1);
        s_rows_read = 0;
        while (!read_pass_into_crop(&cinfo, row)) {
            /* Suspended: the next row continues where this one stopped. */
            if (!release_next_chunk(&s_src)) {
                printf("input ended before the image was complete\n");
                goto cleanup;
            }
        }
        detail = print_crop();

        /* Reads the markers up to the next scan, so this consumes input too. */
        while (!jpeg_finish_output(&cinfo)) {
            if (!release_next_chunk(&s_src)) {
                printf("input ended before the file was complete\n");
                goto cleanup;
            }
        }

        printf("^ scan %d of %d, detail %d\n", cinfo.output_scan_number,
               cinfo.input_scan_number, detail);

        /* Done once the last scan has been rendered and no input is left. */
        if (jpeg_input_complete(&cinfo) &&
                cinfo.input_scan_number == cinfo.output_scan_number) {
            break;
        }
    }

    printf("\ndecoded %d scans from %u bytes, %d suspensions\n",
           cinfo.input_scan_number, (unsigned int)s_src.released, s_suspends);

cleanup:
    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
}

void app_main(void)
{
    printf("Progressive JPEG decoding, one chunk at a time\n");

    decode_progressively(image_prog_jpg_start,
                         (size_t)(image_prog_jpg_end - image_prog_jpg_start));

    printf("\ndone\n");
}
