/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */

#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "esp_cpu.h"
#include "jerror.h"
#include "jpeglib.h"

/* Symbols generated by EMBED_FILES in CMakeLists.txt. */
extern const uint8_t image_jpg_start[] asm("_binary_image_jpg_start");
extern const uint8_t image_jpg_end[] asm("_binary_image_jpg_end");
extern const uint8_t image32x32_jpg_start[] asm("_binary_image32x32_jpg_start");
extern const uint8_t image32x32_jpg_end[] asm("_binary_image32x32_jpg_end");

/*
 * Extended error manager carrying the setjmp recovery point,
 * as recommended by libjpeg's documentation (libjpeg.txt).
 */
struct jpeg_error_mgr_ext {
    struct jpeg_error_mgr pub;
    jmp_buf setjmp_buffer;
};

static void jpeg_error_exit(j_common_ptr cinfo)
{
    struct jpeg_error_mgr_ext *err = (struct jpeg_error_mgr_ext *)cinfo->err;

    (*cinfo->err->output_message)(cinfo);
    /* libjpeg requires error_exit() not to return. */
    longjmp(err->setjmp_buffer, 1);
}

static void print_ppm_header(const struct jpeg_decompress_struct *cinfo)
{
    printf("P6\n%u %u\n%d\n", cinfo->image_width, cinfo->image_height,
           cinfo->data_precision == 12 ? MAXJ12SAMPLE : MAXJSAMPLE);
}

static char pixel_to_ascii(int value)
{
    if (value > 127) {
        return '#';
    }
    if (value > 64) {
        return '+';
    }
    if (value > 32) {
        return '.';
    }
    return ' ';
}

static void print_scanline_ascii(JSAMPROW row, int width, int components)
{
    for (int x = 0; x < width; x++) {
        int value = 0;
        for (int c = 0; c < components; c++) {
            value += row[x * components + c];
        }
        /* Average RGB (or gray) so each pixel becomes one console character. */
        putchar(pixel_to_ascii(value / components));
    }
    putchar('\n');
}

static void decode_embedded_jpeg(const uint8_t *data, size_t len, bool print_ascii)
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;

    /* err must be installed before jpeg_create_decompress(). */
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buffer)) {
        /* A fatal libjpeg error was reported via jpeg_error_exit(). */
        fprintf(stderr, "JPEG decode failed, skipping image\n");
        jpeg_destroy_decompress(&cinfo);
        return;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, (const unsigned char *)data, (unsigned long)len);
    (void)jpeg_read_header(&cinfo, TRUE);
    print_ppm_header(&cinfo);

    const unsigned int start_cycles = (unsigned int)esp_cpu_get_cycle_count();
    if (!print_ascii) {
        printf("jpeg_start_decompress\n");
    }
    jpeg_start_decompress(&cinfo);

    /* One output row: width * components (3 for RGB). */
    const int row_stride = cinfo.output_width * cinfo.output_components;
    JSAMPARRAY buffer = (*cinfo.mem->alloc_sarray)((j_common_ptr)&cinfo, JPOOL_IMAGE, row_stride, 1);

    if (print_ascii) {
        printf("Decoded image 32x32:\n");
    }

    while (cinfo.output_scanline < cinfo.output_height) {
        (void)jpeg_read_scanlines(&cinfo, buffer, 1);
        if (print_ascii) {
            print_scanline_ascii(buffer[0], (int)cinfo.output_width, cinfo.output_components);
        }
    }

    if (!print_ascii) {
        const unsigned int elapsed =
            (unsigned int)(esp_cpu_get_cycle_count() - start_cycles);
        printf("jpeg_finish_decompress, time = %u\n", (elapsed / 100000U) * 100000U);
        printf("jpeg_destroy_decompress\n");
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
}

void app_main(void)
{
    printf("app_main started\n");

    /* 320x240: time the decompress. 32x32: print pixels as ASCII. */
    decode_embedded_jpeg(image_jpg_start, (size_t)(image_jpg_end - image_jpg_start), false);
    decode_embedded_jpeg(image32x32_jpg_start, (size_t)(image32x32_jpg_end - image32x32_jpg_start), true);

    printf("done\n");
}
