/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Unlicense OR CC0-1.0
 *
 * libjpeg-turbo host tests: the in-memory decode pipeline that used to live in
 * the hello_jpeg example, plus a few negative cases. No ESP chip required.
 *
 * The two bundled JPEGs are compiled into the test application with
 * EMBED_FILES in main/CMakeLists.txt. image.jpg is 320x240 and uses the
 * baseline sequential mode; image32x32.jpg is 32x32 and is rendered as ASCII
 * so the decoded pixels are visible in the test log.
 */

#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "jerror.h"
#include "jpeglib.h"
#include "unity.h"

/* Symbols generated by EMBED_FILES in CMakeLists.txt. */
extern const uint8_t image_jpg_start[] asm("_binary_image_jpg_start");
extern const uint8_t image_jpg_end[] asm("_binary_image_jpg_end");
extern const uint8_t image32x32_jpg_start[] asm("_binary_image32x32_jpg_start");
extern const uint8_t image32x32_jpg_end[] asm("_binary_image32x32_jpg_end");

/*
 * Extended error manager carrying the setjmp recovery point,
 * as recommended by libjpeg's documentation (libjpeg.txt).
 */
struct jpeg_error_mgr_ext {
    struct jpeg_error_mgr pub;
    jmp_buf setjmp_buffer;
};

static bool error_exit_called;

static void jpeg_error_exit(j_common_ptr cinfo)
{
    struct jpeg_error_mgr_ext *err = (struct jpeg_error_mgr_ext *)cinfo->err;

    (*cinfo->err->output_message)(cinfo);
    error_exit_called = true;
    /* libjpeg requires error_exit() not to return. */
    longjmp(err->setjmp_buffer, 1);
}

/* Decoded image description filled in by decode_image(). */
struct decoded_image {
    unsigned int width;
    unsigned int height;
    int components;
    size_t bytes;               /* width * height * components of output */
    bool decode_failed;         /* set when libjpeg reported a fatal error */
};

/*
 * Decode a JPEG held in memory with the classic libjpeg API:
 * jpeg_create_decompress() / jpeg_read_header() / jpeg_read_scanlines().
 * Each scanline is folded into a running checksum so the caller can assert
 * that the pixel data actually came out, without keeping a framebuffer.
 */
static uint32_t decode_image(const uint8_t *data, size_t len, J_COLOR_SPACE out_color_space,
                             struct decoded_image *info)
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;
    /* volatile: the setjmp/longjmp pair below can otherwise let the compiler
     * keep this in a register that the longjmp path clobbers. */
    volatile uint32_t checksum = 0;

    memset(info, 0, sizeof(*info));
    error_exit_called = false;

    /* err must be installed before jpeg_create_decompress(). */
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buffer)) {
        /* A fatal libjpeg error was reported via jpeg_error_exit(). */
        info->decode_failed = true;
        jpeg_destroy_decompress(&cinfo);
        return 0;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, (const unsigned char *)data, (unsigned long)len);
    (void)jpeg_read_header(&cinfo, TRUE);

    if (out_color_space != JCS_UNKNOWN) {
        /* Request grayscale (or another conversion) before starting; libjpeg
         * derives output_components from the requested color space. */
        cinfo.out_color_space = out_color_space;
    }
    jpeg_start_decompress(&cinfo);

    info->width = cinfo.output_width;
    info->height = cinfo.output_height;
    info->components = cinfo.output_components;
    info->bytes = (size_t)cinfo.output_width * cinfo.output_height * cinfo.output_components;

    /* One output row: width * components (3 for RGB, 1 for grayscale). */
    const int row_stride = cinfo.output_width * cinfo.output_components;
    JSAMPARRAY buffer = (*cinfo.mem->alloc_sarray)((j_common_ptr)&cinfo, JPOOL_IMAGE, row_stride, 1);

    while (cinfo.output_scanline < cinfo.output_height) {
        (void)jpeg_read_scanlines(&cinfo, buffer, 1);
        for (int i = 0; i < row_stride; i++) {
            /* FNV-1a over every byte of decoded output. */
            checksum = (checksum ^ buffer[0][i]) * 16777619U;
        }
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
    return checksum;
}

static char pixel_to_ascii(int value)
{
    if (value > 127) {
        return '#';
    }
    if (value > 64) {
        return '+';
    }
    if (value > 32) {
        return '.';
    }
    return ' ';
}

/* Print every scanline as one line of ASCII, averaging the color channels. */
static void print_image_ascii(const uint8_t *data, size_t len)
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;

    error_exit_called = false;

    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buffer)) {
        printf("JPEG decode failed\n");
        jpeg_destroy_decompress(&cinfo);
        return;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, (const unsigned char *)data, (unsigned long)len);
    (void)jpeg_read_header(&cinfo, TRUE);
    jpeg_start_decompress(&cinfo);

    const int row_stride = cinfo.output_width * cinfo.output_components;
    JSAMPARRAY buffer = (*cinfo.mem->alloc_sarray)((j_common_ptr)&cinfo, JPOOL_IMAGE, row_stride, 1);

    printf("Decoded image %ux%u:\n", cinfo.output_width, cinfo.output_height);
    while (cinfo.output_scanline < cinfo.output_height) {
        (void)jpeg_read_scanlines(&cinfo, buffer, 1);
        for (unsigned int x = 0; x < cinfo.output_width; x++) {
            int value = 0;
            for (int c = 0; c < cinfo.output_components; c++) {
                value += buffer[0][x * cinfo.output_components + c];
            }
            putchar(pixel_to_ascii(value / cinfo.output_components));
        }
        putchar('\n');
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
}

static size_t embedded_len(const uint8_t *start, const uint8_t *end)
{
    return (size_t)(end - start);
}

/* --------------------------------------------------------------------------
 * Header parsing: dimensions, precision and color space of the bundled images
 * -------------------------------------------------------------------------- */

TEST_CASE("libjpeg-turbo: read header of bundled 320x240 JPEG", "[libjpeg-turbo]")
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;

    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;
    if (setjmp(jerr.setjmp_buffer)) {
        TEST_FAIL_MESSAGE("jpeg_read_header() reported a fatal error");
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, image_jpg_start, (unsigned long)embedded_len(image_jpg_start, image_jpg_end));

    TEST_ASSERT_EQUAL_INT(JPEG_HEADER_OK, jpeg_read_header(&cinfo, TRUE));
    TEST_ASSERT_EQUAL_UINT(320, cinfo.image_width);
    TEST_ASSERT_EQUAL_UINT(240, cinfo.image_height);
    TEST_ASSERT_EQUAL_INT(8, cinfo.data_precision);
    TEST_ASSERT_EQUAL_INT(JCS_YCbCr, cinfo.jpeg_color_space);
    TEST_ASSERT_FALSE(cinfo.progressive_mode);

    jpeg_destroy_decompress(&cinfo);
}

TEST_CASE("libjpeg-turbo: read header of bundled 32x32 JPEG", "[libjpeg-turbo]")
{
    struct jpeg_error_mgr_ext jerr;
    struct jpeg_decompress_struct cinfo;

    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;
    if (setjmp(jerr.setjmp_buffer)) {
        TEST_FAIL_MESSAGE("jpeg_read_header() reported a fatal error");
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, image32x32_jpg_start,
                 (unsigned long)embedded_len(image32x32_jpg_start, image32x32_jpg_end));

    TEST_ASSERT_EQUAL_INT(JPEG_HEADER_OK, jpeg_read_header(&cinfo, TRUE));
    TEST_ASSERT_EQUAL_UINT(32, cinfo.image_width);
    TEST_ASSERT_EQUAL_UINT(32, cinfo.image_height);
    TEST_ASSERT_EQUAL_INT(JCS_YCbCr, cinfo.jpeg_color_space);

    jpeg_destroy_decompress(&cinfo);
}

/* --------------------------------------------------------------------------
 * Full decode of the bundled images
 * -------------------------------------------------------------------------- */

TEST_CASE("libjpeg-turbo: decode bundled 320x240 JPEG", "[libjpeg-turbo]")
{
    struct decoded_image info;
    const size_t len = embedded_len(image_jpg_start, image_jpg_end);

    const uint32_t checksum = decode_image(image_jpg_start, len, JCS_RGB, &info);

    TEST_ASSERT_FALSE(info.decode_failed);
    TEST_ASSERT_EQUAL_UINT(320, info.width);
    TEST_ASSERT_EQUAL_UINT(240, info.height);
    TEST_ASSERT_EQUAL_INT(3, info.components);
    TEST_ASSERT_EQUAL_UINT(320 * 240 * 3, info.bytes);
    /* The image is not uniform, so the checksum must differ from a blank one. */
    TEST_ASSERT_NOT_EQUAL(0, checksum);
}

TEST_CASE("libjpeg-turbo: decode bundled 32x32 JPEG as ASCII", "[libjpeg-turbo]")
{
    struct decoded_image info;
    const size_t len = embedded_len(image32x32_jpg_start, image32x32_jpg_end);

    const uint32_t checksum = decode_image(image32x32_jpg_start, len, JCS_UNKNOWN, &info);

    TEST_ASSERT_FALSE(info.decode_failed);
    TEST_ASSERT_EQUAL_UINT(32, info.width);
    TEST_ASSERT_EQUAL_UINT(32, info.height);
    TEST_ASSERT_EQUAL_INT(3, info.components);
    TEST_ASSERT_NOT_EQUAL(0, checksum);

    /* Render the pixels; the log is the human-readable counterpart to the
     * checksum assertion above. */
    print_image_ascii(image32x32_jpg_start, len);
}

TEST_CASE("libjpeg-turbo: decode bundled 320x240 JPEG as grayscale", "[libjpeg-turbo]")
{
    struct decoded_image info;
    const size_t len = embedded_len(image_jpg_start, image_jpg_end);

    const uint32_t checksum = decode_image(image_jpg_start, len, JCS_GRAYSCALE, &info);

    TEST_ASSERT_FALSE(info.decode_failed);
    TEST_ASSERT_EQUAL_UINT(320, info.width);
    TEST_ASSERT_EQUAL_UINT(240, info.height);
    TEST_ASSERT_EQUAL_INT(1, info.components);
    TEST_ASSERT_EQUAL_UINT(320 * 240, info.bytes);
    TEST_ASSERT_NOT_EQUAL(0, checksum);
}

/* --------------------------------------------------------------------------
 * Error handling: malformed input must come back through error_exit()
 * -------------------------------------------------------------------------- */

TEST_CASE("libjpeg-turbo: truncated JPEG reports an error", "[libjpeg-turbo]")
{
    struct decoded_image info;
    /* Only the first few bytes: not a complete JPEG stream. */
    const size_t len = 16;

    TEST_ASSERT_GREATER_THAN(0, embedded_len(image_jpg_start, image_jpg_end));

    (void)decode_image(image_jpg_start, len, JCS_RGB, &info);

    TEST_ASSERT_TRUE(info.decode_failed);
    TEST_ASSERT_TRUE(error_exit_called);
}

TEST_CASE("libjpeg-turbo: garbage input reports an error", "[libjpeg-turbo]")
{
    static const uint8_t garbage[64] = {0x5a};
    struct decoded_image info;

    (void)decode_image(garbage, sizeof(garbage), JCS_RGB, &info);

    TEST_ASSERT_TRUE(info.decode_failed);
    TEST_ASSERT_TRUE(error_exit_called);
}
