/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: network_scan.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "network_scan.pb-c.h"
void   wifi_scan_start__init
                     (WifiScanStart         *message)
{
  static const WifiScanStart init_value = WIFI_SCAN_START__INIT;
  *message = init_value;
}
size_t wifi_scan_start__get_packed_size
                     (const WifiScanStart *message)
{
  assert(message->base.descriptor == &wifi_scan_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_scan_start__pack
                     (const WifiScanStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_scan_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_scan_start__pack_to_buffer
                     (const WifiScanStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_scan_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiScanStart *
       wifi_scan_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiScanStart *)
     protobuf_c_message_unpack (&wifi_scan_start__descriptor,
                                allocator, len, data);
}
void   wifi_scan_start__free_unpacked
                     (WifiScanStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_scan_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_scan_start__init
                     (ThreadScanStart         *message)
{
  static const ThreadScanStart init_value = THREAD_SCAN_START__INIT;
  *message = init_value;
}
size_t thread_scan_start__get_packed_size
                     (const ThreadScanStart *message)
{
  assert(message->base.descriptor == &thread_scan_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_scan_start__pack
                     (const ThreadScanStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_scan_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_scan_start__pack_to_buffer
                     (const ThreadScanStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &thread_scan_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadScanStart *
       thread_scan_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadScanStart *)
     protobuf_c_message_unpack (&thread_scan_start__descriptor,
                                allocator, len, data);
}
void   thread_scan_start__free_unpacked
                     (ThreadScanStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &thread_scan_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_scan_start__init
                     (CmdScanStart         *message)
{
  static const CmdScanStart init_value = CMD_SCAN_START__INIT;
  *message = init_value;
}
size_t cmd_scan_start__get_packed_size
                     (const CmdScanStart *message)
{
  assert(message->base.descriptor == &cmd_scan_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_scan_start__pack
                     (const CmdScanStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_scan_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_scan_start__pack_to_buffer
                     (const CmdScanStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_scan_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdScanStart *
       cmd_scan_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdScanStart *)
     protobuf_c_message_unpack (&cmd_scan_start__descriptor,
                                allocator, len, data);
}
void   cmd_scan_start__free_unpacked
                     (CmdScanStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmd_scan_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_scan_start__init
                     (RespScanStart         *message)
{
  static const RespScanStart init_value = RESP_SCAN_START__INIT;
  *message = init_value;
}
size_t resp_scan_start__get_packed_size
                     (const RespScanStart *message)
{
  assert(message->base.descriptor == &resp_scan_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_scan_start__pack
                     (const RespScanStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_scan_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_scan_start__pack_to_buffer
                     (const RespScanStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_scan_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespScanStart *
       resp_scan_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespScanStart *)
     protobuf_c_message_unpack (&resp_scan_start__descriptor,
                                allocator, len, data);
}
void   resp_scan_start__free_unpacked
                     (RespScanStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &resp_scan_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_scan_status__init
                     (CmdScanStatus         *message)
{
  static const CmdScanStatus init_value = CMD_SCAN_STATUS__INIT;
  *message = init_value;
}
size_t cmd_scan_status__get_packed_size
                     (const CmdScanStatus *message)
{
  assert(message->base.descriptor == &cmd_scan_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_scan_status__pack
                     (const CmdScanStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_scan_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_scan_status__pack_to_buffer
                     (const CmdScanStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_scan_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdScanStatus *
       cmd_scan_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdScanStatus *)
     protobuf_c_message_unpack (&cmd_scan_status__descriptor,
                                allocator, len, data);
}
void   cmd_scan_status__free_unpacked
                     (CmdScanStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmd_scan_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_scan_status__init
                     (RespScanStatus         *message)
{
  static const RespScanStatus init_value = RESP_SCAN_STATUS__INIT;
  *message = init_value;
}
size_t resp_scan_status__get_packed_size
                     (const RespScanStatus *message)
{
  assert(message->base.descriptor == &resp_scan_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_scan_status__pack
                     (const RespScanStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_scan_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_scan_status__pack_to_buffer
                     (const RespScanStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_scan_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespScanStatus *
       resp_scan_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespScanStatus *)
     protobuf_c_message_unpack (&resp_scan_status__descriptor,
                                allocator, len, data);
}
void   resp_scan_status__free_unpacked
                     (RespScanStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &resp_scan_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_scan_result__init
                     (CmdScanResult         *message)
{
  static const CmdScanResult init_value = CMD_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t cmd_scan_result__get_packed_size
                     (const CmdScanResult *message)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_scan_result__pack
                     (const CmdScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_scan_result__pack_to_buffer
                     (const CmdScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdScanResult *
       cmd_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdScanResult *)
     protobuf_c_message_unpack (&cmd_scan_result__descriptor,
                                allocator, len, data);
}
void   cmd_scan_result__free_unpacked
                     (CmdScanResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wifi_scan_result__init
                     (WifiScanResult         *message)
{
  static const WifiScanResult init_value = WIFI_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t wifi_scan_result__get_packed_size
                     (const WifiScanResult *message)
{
  assert(message->base.descriptor == &wifi_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wifi_scan_result__pack
                     (const WifiScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wifi_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wifi_scan_result__pack_to_buffer
                     (const WifiScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wifi_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WifiScanResult *
       wifi_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WifiScanResult *)
     protobuf_c_message_unpack (&wifi_scan_result__descriptor,
                                allocator, len, data);
}
void   wifi_scan_result__free_unpacked
                     (WifiScanResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wifi_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_scan_result__init
                     (ThreadScanResult         *message)
{
  static const ThreadScanResult init_value = THREAD_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t thread_scan_result__get_packed_size
                     (const ThreadScanResult *message)
{
  assert(message->base.descriptor == &thread_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_scan_result__pack
                     (const ThreadScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_scan_result__pack_to_buffer
                     (const ThreadScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &thread_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadScanResult *
       thread_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadScanResult *)
     protobuf_c_message_unpack (&thread_scan_result__descriptor,
                                allocator, len, data);
}
void   thread_scan_result__free_unpacked
                     (ThreadScanResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &thread_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scan_result__init
                     (ScanResult         *message)
{
  static const ScanResult init_value = SCAN_RESULT__INIT;
  *message = init_value;
}
size_t scan_result__get_packed_size
                     (const ScanResult *message)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_result__pack
                     (const ScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_result__pack_to_buffer
                     (const ScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanResult *
       scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanResult *)
     protobuf_c_message_unpack (&scan_result__descriptor,
                                allocator, len, data);
}
void   scan_result__free_unpacked
                     (ScanResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_scan_result__init
                     (RespScanResult         *message)
{
  static const RespScanResult init_value = RESP_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t resp_scan_result__get_packed_size
                     (const RespScanResult *message)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_scan_result__pack
                     (const RespScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_scan_result__pack_to_buffer
                     (const RespScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespScanResult *
       resp_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespScanResult *)
     protobuf_c_message_unpack (&resp_scan_result__descriptor,
                                allocator, len, data);
}
void   resp_scan_result__free_unpacked
                     (RespScanResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   network_scan_payload__init
                     (NetworkScanPayload         *message)
{
  static const NetworkScanPayload init_value = NETWORK_SCAN_PAYLOAD__INIT;
  *message = init_value;
}
size_t network_scan_payload__get_packed_size
                     (const NetworkScanPayload *message)
{
  assert(message->base.descriptor == &network_scan_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t network_scan_payload__pack
                     (const NetworkScanPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &network_scan_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t network_scan_payload__pack_to_buffer
                     (const NetworkScanPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &network_scan_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetworkScanPayload *
       network_scan_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetworkScanPayload *)
     protobuf_c_message_unpack (&network_scan_payload__descriptor,
                                allocator, len, data);
}
void   network_scan_payload__free_unpacked
                     (NetworkScanPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &network_scan_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wifi_scan_start__field_descriptors[4] =
{
  {
    "blocking",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(WifiScanStart, blocking),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "passive",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(WifiScanStart, passive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_channels",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WifiScanStart, group_channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period_ms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WifiScanStart, period_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_scan_start__field_indices_by_name[] = {
  0,   /* field[0] = blocking */
  2,   /* field[2] = group_channels */
  1,   /* field[1] = passive */
  3,   /* field[3] = period_ms */
};
static const ProtobufCIntRange wifi_scan_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor wifi_scan_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiScanStart",
  "WifiScanStart",
  "WifiScanStart",
  "",
  sizeof(WifiScanStart),
  4,
  wifi_scan_start__field_descriptors,
  wifi_scan_start__field_indices_by_name,
  1,  wifi_scan_start__number_ranges,
  (ProtobufCMessageInit) wifi_scan_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_scan_start__field_descriptors[2] =
{
  {
    "blocking",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ThreadScanStart, blocking),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_mask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanStart, channel_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_scan_start__field_indices_by_name[] = {
  0,   /* field[0] = blocking */
  1,   /* field[1] = channel_mask */
};
static const ProtobufCIntRange thread_scan_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor thread_scan_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadScanStart",
  "ThreadScanStart",
  "ThreadScanStart",
  "",
  sizeof(ThreadScanStart),
  2,
  thread_scan_start__field_descriptors,
  thread_scan_start__field_indices_by_name,
  1,  thread_scan_start__number_ranges,
  (ProtobufCMessageInit) thread_scan_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmd_scan_start__field_descriptors[3] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CmdScanStart, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_scan_start",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CmdScanStart, payload_case),
    offsetof(CmdScanStart, wifi_scan_start),
    &wifi_scan_start__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_scan_start",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CmdScanStart, payload_case),
    offsetof(CmdScanStart, thread_scan_start),
    &thread_scan_start__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_scan_start__field_indices_by_name[] = {
  0,   /* field[0] = net_type */
  2,   /* field[2] = thread_scan_start */
  1,   /* field[1] = wifi_scan_start */
};
static const ProtobufCIntRange cmd_scan_start__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cmd_scan_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdScanStart",
  "CmdScanStart",
  "CmdScanStart",
  "",
  sizeof(CmdScanStart),
  3,
  cmd_scan_start__field_descriptors,
  cmd_scan_start__field_indices_by_name,
  2,  cmd_scan_start__number_ranges,
  (ProtobufCMessageInit) cmd_scan_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_scan_start__field_descriptors[1] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RespScanStart, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_scan_start__field_indices_by_name[] = {
  0,   /* field[0] = net_type */
};
static const ProtobufCIntRange resp_scan_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor resp_scan_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespScanStart",
  "RespScanStart",
  "RespScanStart",
  "",
  sizeof(RespScanStart),
  1,
  resp_scan_start__field_descriptors,
  resp_scan_start__field_indices_by_name,
  1,  resp_scan_start__number_ranges,
  (ProtobufCMessageInit) resp_scan_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmd_scan_status__field_descriptors[1] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CmdScanStatus, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_scan_status__field_indices_by_name[] = {
  0,   /* field[0] = net_type */
};
static const ProtobufCIntRange cmd_scan_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cmd_scan_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdScanStatus",
  "CmdScanStatus",
  "CmdScanStatus",
  "",
  sizeof(CmdScanStatus),
  1,
  cmd_scan_status__field_descriptors,
  cmd_scan_status__field_indices_by_name,
  1,  cmd_scan_status__number_ranges,
  (ProtobufCMessageInit) cmd_scan_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_scan_status__field_descriptors[3] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RespScanStatus, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_finished",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RespScanStatus, scan_finished),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RespScanStatus, result_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_scan_status__field_indices_by_name[] = {
  0,   /* field[0] = net_type */
  2,   /* field[2] = result_count */
  1,   /* field[1] = scan_finished */
};
static const ProtobufCIntRange resp_scan_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor resp_scan_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespScanStatus",
  "RespScanStatus",
  "RespScanStatus",
  "",
  sizeof(RespScanStatus),
  3,
  resp_scan_status__field_descriptors,
  resp_scan_status__field_indices_by_name,
  1,  resp_scan_status__number_ranges,
  (ProtobufCMessageInit) resp_scan_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmd_scan_result__field_descriptors[3] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CmdScanResult, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CmdScanResult, start_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CmdScanResult, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_scan_result__field_indices_by_name[] = {
  2,   /* field[2] = count */
  0,   /* field[0] = net_type */
  1,   /* field[1] = start_index */
};
static const ProtobufCIntRange cmd_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cmd_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdScanResult",
  "CmdScanResult",
  "CmdScanResult",
  "",
  sizeof(CmdScanResult),
  3,
  cmd_scan_result__field_descriptors,
  cmd_scan_result__field_indices_by_name,
  1,  cmd_scan_result__number_ranges,
  (ProtobufCMessageInit) cmd_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wifi_scan_result__field_descriptors[5] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(WifiScanResult, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(WifiScanResult, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WifiScanResult, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(WifiScanResult, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(WifiScanResult, auth),
    &wifi_auth_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wifi_scan_result__field_indices_by_name[] = {
  4,   /* field[4] = auth */
  3,   /* field[3] = bssid */
  1,   /* field[1] = channel */
  2,   /* field[2] = rssi */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange wifi_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor wifi_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WifiScanResult",
  "WifiScanResult",
  "WifiScanResult",
  "",
  sizeof(WifiScanResult),
  5,
  wifi_scan_result__field_descriptors,
  wifi_scan_result__field_indices_by_name,
  1,  wifi_scan_result__number_ranges,
  (ProtobufCMessageInit) wifi_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_scan_result__field_descriptors[7] =
{
  {
    "pan_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, pan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lqi",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, lqi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_addr",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, ext_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, network_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_pan_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, ext_pan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_scan_result__field_indices_by_name[] = {
  1,   /* field[1] = channel */
  4,   /* field[4] = ext_addr */
  6,   /* field[6] = ext_pan_id */
  3,   /* field[3] = lqi */
  5,   /* field[5] = network_name */
  0,   /* field[0] = pan_id */
  2,   /* field[2] = rssi */
};
static const ProtobufCIntRange thread_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor thread_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadScanResult",
  "ThreadScanResult",
  "ThreadScanResult",
  "",
  sizeof(ThreadScanResult),
  7,
  thread_scan_result__field_descriptors,
  thread_scan_result__field_indices_by_name,
  1,  thread_scan_result__number_ranges,
  (ProtobufCMessageInit) thread_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scan_result__field_descriptors[2] =
{
  {
    "wifi_result",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScanResult, result_case),
    offsetof(ScanResult, wifi_result),
    &wifi_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_result",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScanResult, result_case),
    offsetof(ScanResult, thread_result),
    &thread_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_result__field_indices_by_name[] = {
  1,   /* field[1] = thread_result */
  0,   /* field[0] = wifi_result */
};
static const ProtobufCIntRange scan_result__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanResult",
  "ScanResult",
  "ScanResult",
  "",
  sizeof(ScanResult),
  2,
  scan_result__field_descriptors,
  scan_result__field_indices_by_name,
  1,  scan_result__number_ranges,
  (ProtobufCMessageInit) scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_scan_result__field_descriptors[2] =
{
  {
    "net_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RespScanResult, net_type),
    &network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RespScanResult, n_entries),
    offsetof(RespScanResult, entries),
    &scan_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_scan_result__field_indices_by_name[] = {
  1,   /* field[1] = entries */
  0,   /* field[0] = net_type */
};
static const ProtobufCIntRange resp_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor resp_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespScanResult",
  "RespScanResult",
  "RespScanResult",
  "",
  sizeof(RespScanResult),
  2,
  resp_scan_result__field_descriptors,
  resp_scan_result__field_indices_by_name,
  1,  resp_scan_result__number_ranges,
  (ProtobufCMessageInit) resp_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor network_scan_payload__field_descriptors[8] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetworkScanPayload, msg),
    &network_scan_msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetworkScanPayload, status),
    &status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_scan_start",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, cmd_scan_start),
    &cmd_scan_start__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_scan_start",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, resp_scan_start),
    &resp_scan_start__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_scan_status",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, cmd_scan_status),
    &cmd_scan_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_scan_status",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, resp_scan_status),
    &resp_scan_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_scan_result",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, cmd_scan_result),
    &cmd_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_scan_result",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NetworkScanPayload, payload_case),
    offsetof(NetworkScanPayload, resp_scan_result),
    &resp_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned network_scan_payload__field_indices_by_name[] = {
  6,   /* field[6] = cmd_scan_result */
  2,   /* field[2] = cmd_scan_start */
  4,   /* field[4] = cmd_scan_status */
  0,   /* field[0] = msg */
  7,   /* field[7] = resp_scan_result */
  3,   /* field[3] = resp_scan_start */
  5,   /* field[5] = resp_scan_status */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange network_scan_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor network_scan_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetworkScanPayload",
  "NetworkScanPayload",
  "NetworkScanPayload",
  "",
  sizeof(NetworkScanPayload),
  8,
  network_scan_payload__field_descriptors,
  network_scan_payload__field_indices_by_name,
  2,  network_scan_payload__number_ranges,
  (ProtobufCMessageInit) network_scan_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue network_scan_msg_type__enum_values_by_number[6] =
{
  { "TypeCmdScanStart", "NETWORK_SCAN_MSG_TYPE__TypeCmdScanStart", 0 },
  { "TypeRespScanStart", "NETWORK_SCAN_MSG_TYPE__TypeRespScanStart", 1 },
  { "TypeCmdScanStatus", "NETWORK_SCAN_MSG_TYPE__TypeCmdScanStatus", 2 },
  { "TypeRespScanStatus", "NETWORK_SCAN_MSG_TYPE__TypeRespScanStatus", 3 },
  { "TypeCmdScanResult", "NETWORK_SCAN_MSG_TYPE__TypeCmdScanResult", 4 },
  { "TypeRespScanResult", "NETWORK_SCAN_MSG_TYPE__TypeRespScanResult", 5 },
};
static const ProtobufCIntRange network_scan_msg_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex network_scan_msg_type__enum_values_by_name[6] =
{
  { "TypeCmdScanResult", 4 },
  { "TypeCmdScanStart", 0 },
  { "TypeCmdScanStatus", 2 },
  { "TypeRespScanResult", 5 },
  { "TypeRespScanStart", 1 },
  { "TypeRespScanStatus", 3 },
};
const ProtobufCEnumDescriptor network_scan_msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NetworkScanMsgType",
  "NetworkScanMsgType",
  "NetworkScanMsgType",
  "",
  6,
  network_scan_msg_type__enum_values_by_number,
  6,
  network_scan_msg_type__enum_values_by_name,
  1,
  network_scan_msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
