name: Push components to Espressif Component Service

on:
  # For pull requests: perform upload with "--dry-run" argument,
  # i.e. validate that the component passes all checks for being uploaded.
  pull_request:

  # For pushes to master: actually upload the components to the registry.
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: |
          echo "${{ ( github.ref_name != 'master' || github.repository_owner != 'espressif' ) && 'Checking' || 'Uploading' }} components"
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            argtable3
            bdc_motor
            brotli
            catch2
            cbor
            ccomp_timer
            cjson
            coap
            coremark
            dhara
            eigen
            esp_cli
            esp_cli_commands
            esp_daylight
            esp_delta_ota
            esp_encrypted_img
            esp_ext_part_tables
            esp_flash_dispatcher
            esp_gcov
            esp_isotp
            esp_jpeg
            esp_lcd_qemu_rgb
            esp_lcd_touch_cst820
            esp_linenoise
            esp_schedule
            esp_serial_slave_link
            esp_sysview
            expat
            fmt
            freetype
            fusb303b
            iqmath
            jsmn
            json_generator
            json_parser
            led_strip
            libjpeg-turbo
            libpng
            libsodium
            lua
            lz4
            network_provisioning
            nghttp
            onewire_bus
            pcap
            pid_ctrl
            qoi
            qrcode
            quirc
            rx8130ce
            sh2lib
            spi_nand_flash
            spi_nand_flash_fatfs
            supertinycron
            tg28_sw
            thorvg
            touch_element
            unit-test-app
            zlib
          namespace: "espressif"
          # API token will only be available in the master branch in the main repository.
          # However, dry-run doesn't require a valid token.
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          dry_run: ${{ github.ref_name != 'master' || github.repository_owner != 'espressif' }}
